/**
 * prompts/summaryPrompt.js
 *
 * Prompt for generating a structured clinical summary
 * formatted for physician review.
 */

/**
 * Build the system prompt for clinical summary generation.
 * @returns {string}
 */
function buildSystemPrompt() {
  return `You are a clinical documentation assistant. Your task is to produce a structured, professional medical intake summary from patient triage data.

The summary is intended for a qualified healthcare provider — not the patient.

OUTPUT FORMAT — return ONLY valid JSON with this exact structure:
{
  "chiefComplaint": "<one sentence chief complaint>",
  "historyOfPresentIllness": "<2-4 sentences describing symptom onset, character, associated findings>",
  "symptoms": ["<symptom 1>", "<symptom 2>", ...],
  "duration": "<duration if known, else null>",
  "severity": "<severity descriptor>",
  "medicalHistory": ["<condition 1>", ...],
  "medications": ["<medication 1>", ...],
  "allergies": ["<allergy 1>", ...],
  "riskAssessment": {
    "level": "<low|medium|high|critical>",
    "confidence": <0.0-1.0>,
    "reasoning": ["<point 1>", ...]
  },
  "recommendedDepartment": "<department>",
  "redFlags": ["<red flag 1>", ...],
  "suggestedFollowUp": "<recommended next steps>",
  "disclaimer": "This summary was generated by an AI intake assistant and represents a triage recommendation only. Clinical assessment by a qualified healthcare professional is required for diagnosis and treatment."
}

RULES:
1. Write historyOfPresentIllness in professional clinical note style (SOAP-adjacent).
2. Be factual — only include what was reported by the patient.
3. Use "patient reports", "patient denies", "history of" phrasing.
4. Keep chiefComplaint concise: "[Symptom] x [duration]" format where possible.
5. redFlags should only list clinically significant findings that raise urgency.
6. NEVER provide diagnoses or treatment recommendations.`;
}

/**
 * Build the user prompt for summary generation.
 *
 * @param {object} params
 * @param {string[]} params.extractedSymptoms
 * @param {object[]} params.answeredQuestions
 * @param {object}   params.entities
 * @param {object}   params.triageResult — output from triage assessment
 * @param {object[]} params.messages
 * @returns {string}
 */
function buildUserPrompt({ extractedSymptoms, answeredQuestions, entities, triageResult, messages }) {
  const symptomsText = extractedSymptoms.join(', ') || 'None reported';
  const qaText = answeredQuestions.length > 0
    ? answeredQuestions.map((q) => `Q: ${q.question}\nA: ${q.answer}`).join('\n\n')
    : 'None';

  const entitiesText = JSON.stringify(entities || {}, null, 2);
  const triageText = triageResult ? JSON.stringify(triageResult, null, 2) : 'Not yet assessed';

  const conversationText = (messages || [])
    .filter((m) => m.role !== 'system')
    .map((m) => `${m.role.toUpperCase()}: ${m.content}`)
    .join('\n');

  return `Generate a structured clinical intake summary from the following triage session data:

SYMPTOMS: ${symptomsText}

STRUCTURED ENTITIES:
${entitiesText}

CLINICAL INTERVIEW:
${qaText}

TRIAGE ASSESSMENT:
${triageText}

FULL CONVERSATION:
${conversationText}

Produce the JSON clinical summary for physician review.`;
}

module.exports = { buildSystemPrompt, buildUserPrompt };
